spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.hpm.blog.model
  mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql